###  GET Request API 1 Movies
GET http://localhost:3001/movies/


### POST Request API 2 Movies
POST http://localhost:3001/movies/
Content-Type: application/json

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}

### GET Request API 3 Movies
GET http://localhost:3001/movies/46/

### PUT Request API 4 Movies
PUT http://localhost:3001/movies/50/
Content-Type: application/json

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}

###  DELETE Request API 5 movies
DELETE http://localhost:3001/movies/116/


### GET API 6 Directors
GET http://localhost:3001/directors/


### GET API 7 Directors
GET http://localhost:3001/directors/13/movies/

